### PR TITLE
fix: re-enable and update risc0, clean up runner

### LINKED ISSUE #30: Re-enable RISC0
Currently due to compiler tool chain versions, risc0 is now disabled.

I'd ideally get this working again.

### PR DESCRIPTION
**Pull request by austinabell**
Closes #30 

I started to fix this since I wanted to benchmark some alternate zkp languages for my own curiosity, and it ended up being a bit of a rabbit hole to fix this. I'll try to summarize the changes:

- Update toolchain to stable
  - Can't compile bytemuck (risc0 dep) with this toolchain
  - Don't need allocator_api feature for miden bench anymore (stabilized, but too lazy to find out when)
  - If you want this toolchain pinned to a specific version for any reason, I can change
- Enabled risc0 feature for `all`/`all_compilers`
- Update risc0 to `0.18`
  - I'm making some assumptions for where the line is drawn for compile vs prove here based on their APIs. I couldn't quickly find a way to use their APIs in such a way that fits with this crate's traits.
  - **DISCLAIMER: I have no affiliation with the risc0 team**
- Remove unnecessary allocation of the hash in the risc0 blake hash program
- Switch to use `no_std` version of risc0 programs. `std` wasn't needed for anything
- Remove `ZKP::Default` variant; wasn't used or needed
- Remove risc0-log files (assuming it was accidentally committed)

I don't care for this to come in, feel free to close or make any changes you want to this. Just upstreaming this in case it helps :)

### CODE REVIEW

**Comment by mariari** [comment]
Thanks for getting risc0 working again. It was quite out of date and didn't put in the time to properly fix it. I will try it out tomorrow.

The old log files I will likely make a separate topic based from the latest release removing it.

I will be doing some minor changes to the history before merging

Thank you for your work

**Comment by austinabell** [comment]
> The old log files I will likely make a separate topic based from the latest release removing it.
>
> I will be doing some minor changes to the history before merging

No worries and no rush!

**Comment by mariari** [comment]
The code is now merged, I played with the history a bit:

1.  taking a few of the commits and separating them into their own topics (logs deletion, and move to stable rust)
2. I rebased the code on v0.1.0 since that is the latest base
3. removed some of the refactoring of other parts

**Comment by mariari** [comment]
Thank you for your contribution

**Pull request closed without merging**
