### PR TITLE
add Triton VM to benchmarks

### PR DESCRIPTION
**Pull request by jan-ferdinand**

### CODE REVIEW

**Comment by jan-ferdinand** [comment]
Hi there! In trying to add Triton VM to the benchmarks, I'm encountering the following error.

```
error[E0658]: `let...else` statements are unstable
   --> …/triton-vm-0.19.0/src/proof_item.rs:276:9
    |
276 | /         let Some(len) = str.get(0) else {
277 | |             bail!(ProofStreamError::new("empty buffer"))
278 | |         };
    | |__________^
    |
    = note: see issue #87335 <https://github.com/rust-lang/rust/issues/87335> for more information
    = help: add `#![feature(let_else)]` to the crate attributes to enable
```

I'm confused about `let…else` being interpreted as unstable: it is [stable as of Rust v1.65](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html#let-else-statements). Do you have an idea about the reason for this error?

**Comment by mariari** [comment]
Thanks for the patch, I've resolved the issue locally.

The issue comes from the `rust-toolchain` file.

I've updated my file locally to be

```toml
[toolchain]
channel = "nightly-2022-11-03-x86_64-unknown-linux-gnu"
components = [ "rustfmt", "rust-src" ]
targets = [ "wasm32-unknown-unknown" ]
profile = "minimal"
```

However, it seems the code does not compile fully yet

After making one small change I get the following upon build

```rust
3 101 taichi@Gensokyo:~/Documents/Work/Repo/ZKP/zkp-compiler-shootout/shootout/triton git:triton:*? % cargo build
   Compiling triton v0.1.0 (/home/taichi/Documents/Work/Repo/ZKP/zkp-compiler-shootout/shootout/triton)
error[E0599]: no function or associated item named `from_source` found for struct `Program` in the current scope
  --> src/lib.rs:27:18
   |
27 |         Program::from_source(&self.source_code).unwrap()
   |                  ^^^^^^^^^^^
   |                  |
   |                  function or associated item not found in `Program`
   |                  help: there is an associated function with a similar name: `from_code`

error[E0282]: type annotations needed
  --> src/lib.rs:31:13
   |
31 |         let standard_input = self.standard_input.iter().map(|&x| BFieldElement::new(x)).collect();
   |             ^^^^^^^^^^^^^^
...
34 |             vm::simulate(&program, standard_input.clone(), secret_input);
   |                                    -------------- type must be known at this point
   |
help: consider giving `standard_input` an explicit type
   |
31 |         let standard_input: _ = self.standard_input.iter().map(|&x| BFieldElement::new(x)).collect();
   |                           +++

Some errors have detailed explanations: E0282, E0599.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `triton` due to 2 previous errors
```

Is there anything I can do to help this. I'll be updating the rust version on `main` today

**Comment by mariari** [comment]
I believe I got all code compiling for the project, I'm running the benchmarks now (They take quite a while, sadly)

Sorry for any delay, it took me longer to get `risc0` working than I would have liked.

**Comment by jan-ferdinand** [comment]
Thanks for your help! I've updated my code to correct for the mistakes you point out above and have rebased onto the most recent `main` branch.

The (currently) only remaining error I get seems to be related to the Risc0 benchmark:

```rust
   Compiling shootout v0.1.0 (/home/…/zkp-compiler-shootout/shootout)
error[E0308]: mismatched types
  --> src/main.rs:51:30
   |
51 |         ZKP::Risc0(risc::fib(fib_sequence_idx)),
   |                    --------- ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
   |                    |
   |                    arguments to this function are incorrect
   |
note: function defined here
  --> /home/…/zkp-compiler-shootout/shootout/risc/src/lib.rs:47:8
   |
47 | pub fn fib(input: u32) -> Risc {
   |        ^^^
help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
   |
51 |         ZKP::Risc0(risc::fib(fib_sequence_idx.try_into().unwrap())),
   |                                              ++++++++++++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `shootout` due to previous error
```

**Comment by jan-ferdinand** [comment]
> Sorry for any delay

No worries at all. :slightly_smiling_face:

**Comment by mariari** [comment]
> Thanks for your help! I've updated my code to correct for the mistakes you point out above and have rebased onto the most recent `main` branch.
> 
> The (currently) only remaining error I get seems to be related to the Risc0 benchmark:
> 
> ```rust
>    Compiling shootout v0.1.0 (/home/…/zkp-compiler-shootout/shootout)
> error[E0308]: mismatched types
>   --> src/main.rs:51:30
>    |
> 51 |         ZKP::Risc0(risc::fib(fib_sequence_idx)),
>    |                    --------- ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
>    |                    |
>    |                    arguments to this function are incorrect
>    |
> note: function defined here
>   --> /home/…/zkp-compiler-shootout/shootout/risc/src/lib.rs:47:8
>    |
> 47 | pub fn fib(input: u32) -> Risc {
>    |        ^^^
> help: you can convert a `u64` to a `u32` and panic if the converted value doesn't fit
>    |
> 51 |         ZKP::Risc0(risc::fib(fib_sequence_idx.try_into().unwrap())),
>    |                                              ++++++++++++++++++++
> 
> For more information about this error, try `rustc --explain E0308`.
> error: could not compile `shootout` due to previous error
> ```

Looking at your changes, it seems that 

```rust
pub fn fib(input: u32) -> Risc {
```

expects a u32 because

```rust
    pub input: Vec<u32>,
```

The input is a Vector of `u32`'s 

I pointed out the location in a comment on the branch. But a simple conversion to a u32 should fix the issue

**Comment by mariari** [comment]
Thank you for the contribution.

 I've checked out the branch and ran it locally. The code looks fine.

**Pull request merged**
