### PR TITLE
update to Triton VM v0.20

### PR DESCRIPTION
**Pull request by jan-ferdinand**

### CODE REVIEW

**Comment by mariari** [comment]
Looks good, I hope the CI will post the html results this time.

In the future I"ll add feature flags so that one can test only the system(s) they care about to save time when testing new system

**Comment by jan-ferdinand** [comment]
That'd be great. :+1: I must admit that I did not run the benchmarks due to the time it takes. Even compiling everything is quite resource intensive.

**Comment by mariari** [comment]
Yeah, sadly the `riscv` project in particular takes quite a bit to compile, with the proper feature flags in rust, it should be a lot more bearable. I'll probably add a make command for each kind of test as well, to help lower the startup time even more

**Comment by mariari** [comment]
@jan-ferdinand with #26 the compile flags fix the issue you've had completely. feel free to tell me if you want any other fixes

**Pull request merged**
